### ISSUE TITLE
Question: AppContainer?

### ISSUE THREAD

**Issue by lionkeng** [nganbread/bare-minimum-react-hot-rr4-redux#1]
How is this working without the `<AppContainer>` component as documented in the react-hot-loader README file [here](https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md)? Thx.

**Comment by nganbread** [comment]
Not sure. But it looks like [`<AppContainer>`](https://github.com/gaearon/react-hot-loader/blob/9146001a9e8f076ad36669daa3c2bcdfb1631905/src/AppContainer.dev.js) doesn't do much apart from error checking and deep forcing an update. Its possible that there is an edge case that my example won't be able to handle. Perhaps @gaearon can better answer this question?

**Comment by nganbread** [comment]
Anyhow, I've included `<AppContainer>` in this [commit ](https://github.com/nganbread/bare-minimum-react-hot-rr4-redux/commit/ed2273b435fa38f2e9f094034b892072bd5d1df2) now
