### ISSUE TITLE
react-router-redux

### ISSUE THREAD

**Issue by etylsarin** [nganbread/bare-minimum-react-hot-rr4-redux#2]
Seems the [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) has a release compatible with RR4, would be great to see it implemented in this example app.

**Comment by nganbread** [comment]
Will have a look into it tonight, thanks!

**Comment by nganbread** [comment]
Ive given it a go but it doesnt seem to work ootb... 

Following this discussion (https://github.com/reactjs/react-router-redux/issues/454) it seems like the react-router-redux will play a pretty small role in the router/redux functionality as the new react-router api is now declarative. Also, i cant seem to find an example that uses `<BrowserRouter>` or `react-router v4`

**Comment by etylsarin** [comment]
OK, that's a pity. I was hoping for a stable solution putting all the stuff together in an easy way. Feel free to close this issue. Thanks anyway!

**Comment by nganbread** [comment]
Sweet. I might have another look in a few weeks. Things seem to be changing pretty rapidly over there

**Comment by wonbyte** [comment]
thanks @nganbread . This is a great starter repo!
