### ISSUE TITLE
rr4 error Failed context type

### ISSUE THREAD

**Issue by ashraffayad** [nganbread/bare-minimum-react-hot-rr4-redux#3]
Nice work. Thanks for sharing. 

I cloned the repo, 
ran` npm install`, 
ran `npm run dev` and navigated to localhost:8080
to be greeted by this error:
```
Warning: Failed context type: The context `router.push` is marked as required in `Link`, but its value is `undefined`.
    in Link (created by _default)
    in div (created by _default)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by _default)
    in _default
    in Provider
    in AppContainer
```

The error disappears when I remove the `<Link />` components
Must be a bug in React Router 4 Link component

**Comment by ashraffayad** [comment]
I updated to "react-router-dom": "4.0.0" and the issue disappeared :)
Thanks. I will close this one. Maybe you would like to update too.

**Comment by nganbread** [comment]
Thanks for the heads up! Have upgraded my dependencies per your advice
