### ISSUE TITLE
React-Redux RR4 SSR (work in progress. help needed)

### ISSUE THREAD

**Issue by rolele** [nganbread/bare-minimum-react-hot-rr4-redux#4]
Hi there, 
Excellent work with this repo!
Keep up the good work.

I am trying to upgrade this repo to RR4 
https://github.com/CrocoDillon/universal-react-redux-boilerplate/pull/25

I have some trouble that I describe in the PR.
There is not many people experienced with rr4, but you are one of them. any contribution/suggestions is warmly welcomed:
https://github.com/rolele/universal-react-redux-boilerplate

Thanks

**Comment by rolele** [comment]
I fixed the problem I had. If you have any comment on the method I used or if you know a better way to do it and you want to share, please do.
Cheers

**Comment by nganbread** [comment]
Sorry I didn't get back to you earlier!

Im not too well versed with RR4 + server side rendering so I probably wouldn't have been too helpful. Looks like you've fixed your issue anyhow, so good work!
